<?php

	/**
	 * class for Views
	 *
	 * @version 0.1.0
	 * @author Alexys Hegmann "Yagarasu" http://alexyshegmann.com
	 */
	class View extends EventTrigger
	{
		// Template
		protected $template = "";

		// Model holder
		protected $models = array();

		/**
		 * Constructor
		 * @param array $models Assoc array holding the models needed in the view
		 */
		public function __construct($models=array())
		{
			$this->models = $models;
		}

		/**
		 * Registers a model to be used whithin the view
		 * @param  string $modelName     Key used in the template
		 * @param  Object $modelInstance Model to register
		 */
		public function registerModel($modelName, $modelInstance)
		{
			$this->models[$modelName] = $modelInstance;
		}

		/**
		 * Returns the registered model with the $modelName key
		 * @param  string $modelName Key used in the template
		 * @return mixed            The registered model or null if not exists
		 */
		public function getModel($modelName)
		{
			return ($this->modelIsRegistered($modelName)) ? $this->models[$modelName] : null;
		}

		/**
		 * Unregisters a model
		 * @param  string $modelName Key used in the template
		 * @return boolean            True on success, false on error
		 */
		public function unregisterModel($modelName)
		{
			if($this->modelIsRegistered($modelName)) {
				unset($this->models[$modelName]);
				return true;
			}
			return false;
		}

		/**
		 * Checks if a model is registered or not
		 * @param  string $modelName Key used in template
		 * @return boolean            Whether the model is registered or not
		 */
		public function modelIsRegistered($modelName)
		{
			return(array_key_exists($modelName, $this->models));
		}

		/**
		 * Loads from a url a template file
		 * @param  string $templateUrl Route to template
		 * @return boolean              True on success, false on error
		 */
		public function loadTemplate($templateUrl)
		{
			if(preg_match('/^[a-zA-Z]+\:\/\//i', $templateUrl)===1) throw new Exception("You can't import a template with an absolute route.");
			global $cfg;
			$reqPath = $cfg['dirs']['app'].$templateUrl;
			if(is_readable($reqPath)) {
				$this->template = @file_get_contents($reqPath);
				if($this->template===false) {
					$this->template = "";
					$this->triggerEvent("TEMPLATELOAD_ERROR", array(
						"templateUrl"	=> $templateUrl
					));
					return false;
				}
				$this->triggerEvent("TEMPLATELOADED", array(
					"templateUrl"	=> $templateUrl
				));
				return true;
			}
		}

		/**
		 * Returns the text generated by parsing the special tags
		 * @param string $template A string containing or not special tags. If null given, current loaded template is used.
		 * @return string Final text
		 */
		public function parse($template=null)
		{
			$template = ($template===null) ? $this->template : $template;
			$pattern = ''
				.'~\{\s*'									// ~{
				.'(?P<cmd>\$?\w+)(?:\:(?P<subcmd>\w+))?\s*'	// [$]foo[:bar]
				.'(?P<attrs>\w+=\".*\")*\s*'				// attrn="attrv" ...
				.'(\}(?P<cont>.*?)\{\1)?\s*'			// [} ... {foo]
				.'\}~';										// }~
			return preg_replace_callback('/'.$pattern.'/mis', array($this,'parseSingleTag'), $template);
		}

		/**
		 * Echo wrapper for parse()
		 */
		public function render()
		{
			echo $this->parse();
		}

		private function parseSingleTag($matches)
		{
			$args['cmd'] = $matches['cmd'];
			$args['subcmd'] = (isset($matches['subcmd'])) ? $matches['subcmd'] : null;
			$args['attrs'] = (isset($matches['attrs'])) ? $this->parseTagAttributes($matches['attrs']) : array();
			$args['cont'] = (isset($matches['cont'])) ? trim($matches['cont']) : '';
			if(strpos($args['cmd'],	"$")!==false) {
				$args['cmd'] = substr($args['cmd'], 1);
				return $this->handleTag_label($args);
			} else {
				$callback = 'handleTag_'.$args['cmd'];
				if(!is_callable(array($this, $callback))) return $matches[0];
				return call_user_func(array($this, $callback), $args);
			}
		}

		private function parseTagAttributes($attributes)
		{
			$pattern = '(?P<attrname>\w+)=\"(?P<attrval>[^\"]*)\"';
			$matches = array();
			preg_match_all('/'.$pattern.'/i', $attributes, $matches);
			$attrs = array();
			foreach ($matches['attrname'] as $idx=>$attrname) {
				$attrs[$attrname] = $matches['attrval'][$idx];
			}
			return $attrs;
		}

		private function handleTag_label($opts=array())
		{
			$opts = mergeParamsArray($opts, array(
				'cmd'		=> '',
				'subcmd'	=> ''
			));
			if($opts['cmd']===null||!$this->modelIsRegistered($opts['cmd'])) return "[CRVIEW] Parse error. Model '".$opts['cmd']."' not found on the registered models of this view.";
			if(!isset($this->getModel($opts['cmd'])->$opts['subcmd'])) return "[CRVIEW] Parse error. Property '".$opts['cmd']."' not found in '".$opts['cmd']."'.";
			
			return $this->getModel($opts['cmd'])->$opts['subcmd'];
		}

		private function handleTag_view($opts=array())
		{
			$opts = mergeParamsArray($opts, array(
				'attrs'		=> array()
			));
			if(!isset($opts['attrs']['src'])) return "[CRVIEW] Parse error. Missing 'src' attribute.";
			
			$newView = new View($this->models);
			if(!$newView->loadTemplate($opts['attrs']['src'])) return "[CRVIEW] Error. Couldn't load '".$opts['attrs']['src']."'.";
			return $newView->parse();
		}

		private function handleTag_foreach($opts=array())
		{
			$opts = mergeParamsArray($opts, array(
				'attrs'		=> array(),
				'cont'		=> ''
			));
			if(!isset($opts['attrs']['collection'])) return "[CRVIEW] Error. Collection to iterate not set.";
			$collection = $opts['attrs']['collection'];
			$cur = (isset($opts['attrs']['as'])) ? $opts['attrs']['as'] : 'item';
			if(!$this->modelIsRegistered($collection)) return "[CRVIEW] Parse error. Model '".$collection."' not found on the registered models of this view.";
			$final = "";
			if($this->modelIsRegistered($cur)) $final .= "<!-- [CRVIEW] Warning. Iterator name holder is currently used. This will override, then unregister the model named '".$cur."' -->\n";
			$nView = new View($this->models);
			foreach ($this->getModel($collection)->toArray() as $itm) {
				$nView->registerModel($cur, $itm);
				$final .= $nView->parse($opts['cont']);
				$nView->unregisterModel($cur);
			}
			return $final;
		}
	}

?>